Authentication
keensam04/autohome pull request #43
Opened 2020-04-30 02:14 UTC by misdaque

Authentication by Google...

2020-04-30 02:15 UTC, misdaque commented
Closes #43

2020-04-30 02:53 UTC, keensam04 requested changes

2020-04-30 02:53 UTC, keensam04 commented on pom.xml
> +            <version>2.2.2.RELEASE</version>
remove version

2020-04-30 02:53 UTC, keensam04 commented on pom.xml
> +<!--        <dependency>
remove commented dependency

2020-04-30 02:53 UTC, keensam04 commented on pom.xml
> +            <version>0.9.0</version>
move version to properties

2020-04-30 02:53 UTC, keensam04 commented on src/main/java/com/autohome/Main.java
> +
remove commented code

2020-04-30 02:53 UTC, keensam04 commented on src/main/java/com/autohome/config/SecurityConfig.java
> +       /* http.authorizeRequests()
remove commented code

2020-04-30 02:53 UTC, keensam04 commented on src/main/java/com/autohome/service/UserService.java
> +/*    @Override
remove commented code

2020-04-30 02:53 UTC, keensam04 commented on src/main/resources/application.properties
> +#security.oauth2.client.project_id=zinc-prism-275020
remove commented block

2020-04-30 02:53 UTC, keensam04 commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.clientId=750505933588-ns93dn1hlkfj54bu6e7eg4p9m8hckb40.apps.googleusercontent.com
remove credentials from prop file. to be configured on the server

2020-05-14 04:18 UTC, keensam04 commented
Deprecated by #44

2020-05-14 04:18 UTC, closed without merging